# с билдингом (автор: ИИ)
name: MFk2

on: 
  push:
    branches:
      - main
  #workflow_dispatch

env:
  SERVER_HOST: '85.28.47.165'
  SERVER_USER: root
  SERVER_PATH: /var/www/client/

jobs:
  deployJobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # или нужная версия Node.js

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: ng build 

      - name: Setup SSH key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.PKEY }}" > $HOME/.ssh/key
          chmod 600 $HOME/.ssh/key

      - name: Deploy built files to server
        run: |
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete ./public ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}

      # - name: Clean up and finalize deployment on server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ env.SERVER_HOST }}
      #     username: ${{ env.SERVER_USER }}
      #     key: ${{ secrets.PKEY }}
      #     script: |
      #       rm -rf /var/www/client/inst/.git/
      #       rm -rf /var/www/client/inst/.github/
      #       rm /var/www/client/inst/.gitignore
      #       cp -r /var/www/client/inst/public/* /var/www/client/